config/routes.rb
Rails.application.routes.draw do
  # Define devise routes for users
  devise_for :users

  # Define routes for users, categories, and expenses
  resources :users do
    resources :categories, except: %i[edit update] do
      resources :expenses, only: %i[new create destroy]
    end
  end

  # Defines the root path route ("/")
  unauthenticated do  # Define the root route for non-logged-in users
    root 'users#index', as: :unauthenticated_root
  end

  authenticated :user do  # Define the root route for logged-in users
    root 'categories#index', as: :authenticated_root
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    # Manage their own profile
    can :manage, User, id: user.id

    # Manage their own expenses
    can :manage, Expense, author_id: user.id

    # Manage their own categories
    can :manage, Category, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :icon, presence: true, length: { maximum: 300 }
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :categories, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :expenses, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :set_category, only: %i[show destroy]

  def index
    @user = current_user
    @categories = @user.categories.order(created_at: :desc)
    @expenses = current_user.expenses
  end

  def show
    @expenses = @category.expenses.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.new(category_params)

    if @category.save
      flash[:notice] = 'Category added successfully'
      redirect_to user_categories_path
    else
      flash[:alert] = 'Please provide a valid category Name & Icon'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @category.expenses.empty?
      @category.destroy
      flash[:notice] = 'Category has been successfully removed'
    else
      flash[:alert] = 'Error deleting category, it has associated expenses'
    end

    redirect_to user_categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  load_and_authorize_resource
  before_action :set_category, only: %i[new create]

  def new
    @expense = @category.expenses.build
  end

  def create
    @expense = @category.expenses.build(expense_params)
    @expense.author = current_user

    if @expense.save
      flash[:notice] = 'Expense added successfully'
      redirect_to user_category_path(@category.user, @category)
    else
      flash[:alert] = 'Error creating the expense'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @expense = Expense.find(params[:id])
    if @expense.destroy
      flash[:notice] = 'Expense has been successfully removed'
    else
      flash[:alert] = 'Error deleting expense'
    end

    redirect_to request.referrer || user_categories_path
  end

  private

  def set_category
    @category = current_user.categories.find(params[:category_id])
  end

  def expense_params
    params.require(:expense).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<section>
  <div class="sticky-top">
    <nav class="nav-header w-100 p-3 d-flex justify-content-between align-items-end">
      <%= button_to destroy_user_session_path, method: :delete, class:"btn bg-transparent border-0 p-0" do %>
        <i class="bi bi-box-arrow-left fs-5"></i>
      <% end %>
      <h1 class="text-uppercase text-center fs-5 mx-0 mt-4 mb-0">Categories</h1>
      <i class="bi bi-search fs-5"></i>
    </nav>
    
    <div class="d-flex justify-content-between align-items-center mb-3 px-3 py-2 bg-white border-bottom border-2 border-light-subtle">
        <h2 class="fs-5 pt-2">Overall Budget</h2>
        <span class="category-amount fw-bold"><%= number_to_currency(@expenses.sum(&:amount)) %></span>
    </div>
  </div>

  <article class="categories-container d-flex flex-column justify-content-between px-3">
    <% if @categories.count > 0 %>
      <%= render "shared/category" %>
    <% else %>
      <p class="d-flex justify-content-center align-items-center p-3">You have no categories added yet. Please click on "Add New Category" to proceed!</p>
    <% end %>
  </article>

  <div class='add-category-btn text-center'>
    <%= link_to "Add New Category", new_user_category_path(current_user), class: 'new-category-btn border border-light-subtle text-light text-uppercase' %>
  </div>
</section>

app/views/categories/new.html.erb
<section>
  <nav class="sticky-top nav-header px-1 pb-2 pt-4">
    <div class=" m-auto row align-items-end mt-1">
      <%= link_to user_categories_path, class:"text-white btn-back col" do %>
        <i class="bi bi-arrow-left"></i>
      <% end %>
      <h1 class="text-uppercase text-center fs-5 col-7 ">New Category</h1>
      <i class="bi bi-qr-code-scan mb-1 pb-1 col text-end"></i>
    </div>
  </nav>

  <%= form_with model: @category, url: user_categories_path(current_user), scope: :category, class: "form_container gap-0" do |f| %>
    <div class="input-group py-2 mb-3">
      <%= f.label :name, class: "input-group-text" %>
      <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control" %>
    </div>

    <div class="input-group py-2 mb-3">
      <%= f.label :icon, class: "input-group-text" %>
      <%= f.text_field :icon, autocomplete: "icon", class: "form-control" %>
    </div>

    <%= f.submit "Add Category", class: "btn my-2" %>
  <% end %>
</section>

app/views/categories/show.html.erb
<section>
  <div class="sticky-top">
    <nav class="nav-header px-1 pb-2 pt-4">
      <div class="m-auto row align-items-end mt-1">
        <%= link_to user_categories_path, class:"text-white btn-back col" do %>
          <i class="bi bi-arrow-left"></i>
        <% end %>
        <h1 class="text-uppercase text-center fs-5 col-7 ">Expenses</h1>
        <i class="bi bi-search fs-5 mb-1 pb-1 col text-end"></i>
      </div>
    </nav>
      
    <div class="d-flex justify-content-between align-items-center mb-3 px-3 py-2 bg-white border-bottom border-2 border-light-subtle">
        <h2 class="fs-5 pt-2">
          <%= image_tag @category.icon, alt: "category_icon", style: "width: 1.65rem;" %>
          <%= @category.name %> Budget
        </h2>
        <span class="category-amount fw-bold"><%= number_to_currency(@expenses.sum(&:amount)) %></span>
    </div>
  </div>

  <article class="expenses-container d-flex flex-column justify-content-between px-3">
    <% if @expenses.count > 0 %>
      <%= render "shared/expense" %>
    <% else %>
      <p class="d-flex justify-content-center align-items-center p-3" >You have no expenses added to this category yet. Please click on 'Add New Expense' to proceed!</p>
    <% end %>
  </article>

  <div class='add-expense-btn text-center'>
    <%= link_to "Add New Expense", new_user_category_expense_path(current_user, @category), class: 'new-expense-btn border border-light-subtle text-light text-uppercase' %>
  </div>
</section>

app/views/expenses/new.html.erb
<section>
  <nav class="sticky-top nav-header px-1 pb-2 pt-4">
    <div class=" m-auto row align-items-end mt-1">
      <%= link_to user_category_path(current_user, @category), class:"text-white btn-back col" do %>
        <i class="bi bi-arrow-left"></i>
      <% end %>
      <h1 class="text-uppercase text-center fs-5 col-7 ">New Expense</h1>
      <i class="bi bi-qr-code-scan mb-1 pb-1 col text-end"></i>
    </div>
  </nav>

  <%= form_with model: @expense, url: user_category_expenses_path(current_user, @category), method: :post, scope: :expense, class: 'form_container gap-0' do |f| %>

    <div class="input-group py-2 mb-3">
      <%= f.label :name, class: "input-group-text" %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control' %>
    </div>

    <div class="input-group py-2 mb-3">
      <%= f.label :amount, class: "input-group-text" %><br />
      <%= f.number_field :amount, class: 'form-control' %>
    </div>

    <div class="input-group py-2 mb-3">
      <span class="input-group-text"> Categories </span>
      <div class='form-control'>
        <% current_user.categories.each do |category| %>
          <div class="form-check">
            <%= check_box_tag "expense[category_ids][]", category.id, false, class: 'form-check-input', id: "category_#{category.id}" %>
            <label class="form-check-label" for="category_<%= category.id %>">
              <%= category.name %>
            </label>
          </div>
        <% end %>
      </div>
    </div>

    <%= f.submit "Add Expense", class: 'btn my-2' %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget Tracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body class="bg-body-tertiary">
    <main>
      <% if flash[:notice] %>
        <p class="notice"><%= flash[:notice] %></p>
      <% elsif flash[:alert] %>
        <p class="alert"><%= flash[:alert] %></p>
      <% end %>
    <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_category.html.erb
<% @categories.each do |category| %>
  <div class="px-3 py-3 mb-3 bg-body border border-2 border-light-subtle">
    <%= link_to user_category_path(current_user, category), class: "text-decoration-none" do %>
      <div class="d-flex align-items-center justify-content-between gap-3">
        <%= image_tag category.icon, alt: "category_icon", class:"category-icon" %>

        <div class="flex-grow-1">
          <div class="d-flex justify-content-between align-items-center mb-2">
            <h5 class="title mb-0"><%= category.name %></h5>
            <span class="category-amount fw-bold"><%= number_to_currency(category.expenses.sum(&:amount)) %></span>
          </div>
          <div class="d-flex justify-content-between align-items-center">
            <span class="date fs-6"><%= category.created_at.strftime('%d %b %Y') %></span>
          </div>
        </div>
      </div>
    <% end %>

    <%= button_to "Delete", user_category_path(current_user, category), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn delete-btn p-0 border-0 bg-transparent btn-link link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %>
  </div>
<% end %>

app/views/shared/_expense.html.erb
<% @expenses.each do |expense| %>
  <div class="px-3 py-3 mb-3 bg-body border border-2 border-light-subtle d-flex flex-column">
    <div class="d-flex justify-content-between align-items-center mb-2">
      <h5 class="title mb-0"><%= expense.name %></h5>
      <span class="expense-amount fw-bold"><%= number_to_currency(expense.amount) %></span>
    </div>
    <div class="d-flex justify-content-between align-items-center">
      <span class="date fs-6"><%= expense.created_at.strftime('%d %b %Y at %I:%M%P') %></span>
      <%= button_to "Delete", user_category_expense_path(current_user, @category, expense), method: :delete, class: "btn p-0 border-0 bg-transparent btn-link link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<section class="splash-container">
  <h1 class="fst-italic fw-semibold">Budget Trackie <br>
    <i class="bi bi-bar-chart-line"></i>
  </h1>

  <div class="button-container text-uppercase text-center">
    <%= link_to 'Log In', new_user_session_path, class: 'btn' %>
    <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-secondary bg-transparent' %>
  </div>
</section>